services:
  whisper-api:
    container_name: whisper-api
    build: .
    ports:
      - "3443:8000"
    env_file:
      - .env
    volumes:
      - ./models:/root/.cache/huggingface # Cache models so they don't redownload
    restart: unless-stopped
